version: '3.8'

services:
  task-manager-prod_mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: task_manager
      MYSQL_USER: TASKAPP
      MYSQL_PASSWORD: TaskAppPassword123!
      MYSQL_ROOT_PASSWORD: RootSecurePassword456!
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.tipo == db  # Força a rodar APENAS na VM de banco

  task-manager-prod_backend:
    image: victor584198156/taskmanager-backend:v1
    environment:
      DB_HOST: task-manager-prod_mysql # Usa o DNS interno do Swarm
      DB_USER: TASKAPP
      DB_PASSWORD: TaskAppPassword123!
      DB_NAME: task_manager
      PORT: 5000
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.tipo == app # Força a rodar APENAS na VM de app

  task-manager-prod_frontend:
    image: victor584198156/taskmanager-frontend:v1
    environment:
      API_URL: http://task-manager-prod_backend:5000
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.tipo == app # Força a rodar APENAS na VM de app

networks:
  app-network:
    driver: overlay
    attachable: true

volumes:
  db_data:
    driver: local
