version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: task_manager
      MYSQL_USER: TASKAPP
      MYSQL_PASSWORD: TaskAppPassword123!
      MYSQL_ROOT_PASSWORD: RootSecurePassword456!
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    image: victor584198156/taskmanager-backend:latest
    environment:
      DB_HOST: db
      DB_USER: TASKAPP
      DB_PASSWORD: TaskAppPassword123!
      DB_NAME: task_manager
      PORT: 3000
      NODE_ENV: production
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: victor584198156/taskmanager-frontend:latest
    environment:
      API_URL: http://backend:3000
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - app-network
    configs:
      # Aponta para a nova versão da configuração distribuída do Swarm
      - source: nginx_config_v2
        target: /etc/nginx/nginx.conf
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: overlay
    attachable: true

volumes:
  db_data:
    driver: local

# O Swarm vai ler o arquivo nginx.conf do Git e criar o objeto injetável dentro das VMs
configs:
  nginx_config_v2:
    file: ./nginx.conf
