name: Docker Build e Push Automático

on:
  push:
    branches: [ "main" ] # Dispara sempre que você atualizar a branch main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push do Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend # Altere para a pasta onde está o seu frontend
          push: true
          tags: victor584198156/taskmanager-frontend:latest # Usando :latest agora

      - name: Build e Push do Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend # Altere para a pasta onde está o seu backend
          push: true
          tags: victor584198156/taskmanager-backend:latest # Usando :latest agora
